### ISSUE TITLE
Investigation - Align page structure and hierarchy with GDS Blog pages 

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-blog#18]
Ticket as a placeholder for some investigative actions around aligning the current blog site structure with that used by GDS.
Queries and observations to be considered when doing so:
1: Page title, Banner title, and Main title, mismatch. (Digital Shared Services - Enterprise and Solution Architecture; Digital Shared Services Blog; Blog Enterprise Architecture). Suggest that these should be the same? 
2: Is there more than one blog anticipated? The general hierarchy of the site doesn't appear to be correct if there’s only one blog anticipated (linked to the above query).  Should there be a central 'Blogs' page, from which the user links to the EA Blog?
3: On the GDS equivalent blog, there's no "Blogs" text in the banner. Should this be removed from the DSS site, if it serves no purpose? 
4: On the GDS site, the "Blog" heading at the top of the page serves as a link to the 'Blogs home', and the title "Government Digital Service" is hyperlinked as a Home for the current blog. Should the DSS site match this format?

**Comment by StephenPatterson-DSS** [comment]
Partially complete. No further blogs in the immediate future, so 2 has not been addressed.

**Comment by JamesONeill-DoF** [comment]
Closing - no further blogs anticipated at present.
