### ISSUE TITLE
Bug - Blog Accessibility Statement requires some re-work. 

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-blog#22]
The site accessibility statement requires some additional work:

1: There are no contact details provided for requesting an accessible format. There should be.
2: The statement links to EASS. This is non-applicable in Northern Ireland (Same with Equality and Human Rights Commission (EHRC)). To be replaced with relevant links (e.g., https://www.equalityni.org/help  AND  https://www.equalityni.org/Home).
3: Non-accessible content section needs updated.
4: Disproportionate is spelt incorrectly.
5: Accessibility (in the page title) is spelt incorrectly.
6: Accessible is spelt incorrectly in the text body: "Parts of this website are not fully accessbile."

**Comment by StephenPatterson-DSS** [comment]
Accessibility audit has been performed and issues above addressed.
