### ISSUE TITLE
Bug - General Bucket for spelling errors across the site.

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-blog#23]
Cookies page - spelling error: "Thes cookies are not used to identify you personally". 
Landing page spelling error : "For a quick overview visit the 2019 conference webstite and see who you can recognise in the gallery!" 
Audit service and UT article - Spelling error: "funneled" - should be funnelled?

**Comment by StephenPatterson-DSS** [comment]
For info: funneled was found in API Gateway launch article.

**Comment by JamesONeill-DoF** [comment]
Re-checked each of these, and they've all now been resolved successfully. Closing the ticket.
