### ISSUE TITLE
Feature - Audit and UT article - Use of 'Private Beta' requires explanation.

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-blog#24]
Audit and UT article - The post mentions that these apps are in private beta, but I'm not sure that it's explained anywhere what this means. Suggest including an explanation.

**Comment by StephenPatterson-DSS** [comment]
The developer portal article and the architecture catalogue article as contained this phrase.

Added link to GDS description of beta, in all 3 articles, which includes private beta.

**Comment by JamesONeill-DoF** [comment]
Linked article describing the beta phase. Closing this ticket as resolved.
